import streamlit as st

nifty500_by_industry = {
    "Financial Services": [
        "360ONE","AUBANK","AAVAS","ABCAPITAL","ABFRL","ANGELONE","ARE&M",
        "AXISBANK","BAJFINANCE","BAJAJFINSV","BAJAJHLDNG","BANDHANBNK",
        "BANKBARODA","BANKINDIA","CANBK","CANFINHOME","CHOLAFIN","CUB",
        "CAMS","CITYUNIONBNK","FEDERALBNK","HDFCBANK","HDFCAMC","HDFCLIFE",
        "ICICIBANK","ICICIGI","ICICIPRULI","IDFCFIRSTB","IIFLWAM","INDIANBANK",
        "INDUSINDBK","IRFC","J&KBANK","KOTAKBANK","LICHSGFIN","LTIM","LTF","M&MFIN",
        "MASFIN","MAXHEALTH","MCX","PFC","PNB","REC","SBICARD","SBILIFE","SBIN",
        "SHRIRAMFIN","SIS","SUNDARMFIN","TMB","UNIONBANK","YESBANK"
    ],

    "Information Technology": [
        "TCS","INFY","WIPRO","HCLTECH","LTTS","LTIM","MINDACORP","PERSISTENT",
        "MPHASIS","COFORGE","ZENSARTECH","KPITTECH","TATAELXSI","TECHM"
    ],

    "FMCG": [
        "BRITANNIA","DABUR","HUL","GODREJCP","COLPAL","MARICO","TATACONSUM",
        "NESTLEIND","ITC","EMAMILTD","Zyduswell","RADICO","VBL","UBL"
    ],

    "Healthcare": [
        "APOLLOHOSP","ABBOTINDIA","ALKEM","ASTRAL","AUROPHARMA","BIOCON",
        "CIPLA","DIVISLAB","DRREDDY","FORTIS","GLAND","GLAXO","GRANULES",
        "JBCHEPHARM","LALPATHLAB","LUPIN","METROPOLIS","NATCOPHARM","PFIZER",
        "SANOFI","SUNPHARMA","SYNGENE","TORNTPHARM","ZYDUSLIFE"
    ],

    "Energy": [
        "ADANIGREEN","ADANITRANS","ADANIPOWER","BPCL","GAIL","GEPIL","IOC",
        "NTPC","ONGC","RELIANCE","TATAPOWER","TORNTPOWER","POWERGRID","COALINDIA"
    ],

    "Metals & Mining": [
        "HINDALCO","JSWSTEEL","NMDC","NATIONALUM","SAIL","TATASTEEL","VEDL","JINDALSTEL"
    ],

    "Automobile & Auto Components": [
        "ASIANPAINT","APOLLOTYRE","ASHOKLEY","BAJAJ-AUTO","BALKRISIND","BHARATFORG",
        "EICHERMOT","HEROMOTOCO","M&M","MARUTI","MRF","TVSMOTOR","TIINDIA","TATAMOTORS"
    ],

    "Construction": [
        "DLF","GODREJPROP","LODHA","OBEROIRLTY","PRESTIGE","PHOENIXLTD","SOBHA","LT","ULTRACEMCO"
    ],

    "Capital Goods": [
        "ABB","AIAENG","APARINDS","BEL","BHARATDYNAMICS","BHEL","COCHINSHIP",
        "ELGIEQUIP","HAVELLS","KEI","KIRLOSBROS","POLYCAB","THERMAX","SIEMENS"
    ],

    "Chemicals": [
        "AARTIIND","AETHER","ALKYLAMINE","ATUL","BALAMINES","BERGEPAINT",
        "NOCIL","PIIND","SRF","TATACHEM","UPL","VINATIORGA","DEEPAKNTR"
    ],

    "Services": [
        "BLS","CLEAN","IREDA","IRCTC","QUESS","SIS","TEAMLEASE"
    ],

    "Media Entertainment": [
        "ZEEL","PVRINOX","SUNTV","TVTODAY","NETWORK18","ADANIENT"
    ],

    "Telecom": [
        "BHARTIARTL","IDEA","TATATELE"
    ],

    "Realty": [
        "BRIGADE","CANFINHOME","INDIABULLSREAL","MAJESCO","NBCC"
    ],

    "Consumer Durables": [
        "BAJAJELEC","DIXON","VGUARD","RAJESHEXPO","HAVELLS","TITAN"
    ],

    "Retail": [
        "DMART","VBL","TRENT","RELIANCERETAIL","NYKAA","GRASIM","HINDUNILVR"
    ],

    "Transportation": [
        "CONCOR","DELHIVERY","BLUEDART","GATI","ALLCARGO","ADANIPORTS"
    ]
}


def get_companies():
    companies = [
"360ONE","3MINDIA","ABB","ACC","AIAENG","APLAPOLLO","AUBANK","AARTIIND","AAVAS",
"ABBOTINDIA","ACE","ADANIENSOL","ADANIENT","ADANIGREEN","ADANIPORTS","ADANIPOWER",
"ATGL","AWL","ABCAPITAL","ABFRL","AEGISLOG","AETHER","AFFLE","AJANTPHARM",
"APLLTD","ALKEM","ALKYLAMINE","ALLCARGO","ALOKINDS","ARE&M","AMBER","AMBUJACEM",
"ANANDRATHI","ANGELONE","ANURAS","APARINDS","APOLLOHOSP","APOLLOTYRE","APTUS",
"ASAHIINDIA","ASHOKLEY","ASIANPAINT","ASTERDM","ASTRAZEN","ASTRAL","ATUL","AUROPHARMA",
"AVANTIFEED","DMART","AXISBANK","BEML","BLS","BSE","BAJAJ-AUTO","BAJFINANCE",
"BAJAJFINSV","BAJAJHLDNG","BALAMINES","BALKRISIND","BALRAMCHIN","BANDHANBNK",
"BANKBARODA","BANKINDIA","BATAINDIA","BAYERCROP","BBTC","BDL","BEL","BERGEPAINT",
"BHARATFORG","BHARATRAS","BHARTIARTL","BHEL","BIOCON","BIRLACORPN","BIRLACABLE",
"BLUEDART","BBL","BOSCHLTD","BRIGADE","BSOFT","BRITANNIA","MAPMYINDIA","TTML",
"CANBK","CANFINHOME","CAMS","CAPLIPOINT","CARBORUNIV","CASTROLIND","CCL","CCIL",
"CEATLTD","CENTURYTEX","CERA","CESC","CGCL","CGPOWER","CHAMBLFERT","CHEMPLASTS",
"CHOLAFIN","CIPLA","CLEAN","COALINDIA","COCHINSHIP","COFORGE","COLPAL","CRAFTSMAN",
"CRISIL","CROMPTON","CUB","CUMMINSIND","CYIENT","DLF","DABUR","DALBHARAT","DATAPATTNS",
"DEEPAKFERT","DEEPAKNTR","DELHIVERY","DEVYANI","DISHTV","DIVISLAB","DIXON","DOMS",
"DREDGECORP","DRREDDY","EIDPARRY","EICHERMOT","EIHOTEL","ELGIEQUIP","EMAMILTD",
"ENDURANCE","ENGINERSIN","EQUITASBNK","ERIS","ESCORTS","EXIDEIND","FEDERALBNK",
"FINEORG","FIVESTAR","FORTIS","GARFIBRES","GAIL","GALAXYSURF","GICRE","GILLETTE",
"GLAND","GLAXO","GLENMARK","GLS","GMRINFRA","GODFRYPHLP","GODREJAGRO","GODREJCP",
"GODREJIND","GODREJPROP","GRANULES","GRAPHITE","GRASIM","GESHIP","GREAVESCOT",
"GREENPANEL","GREENPLY","GRINDWELL","GUJGASLTD","GNFC","GPIL","GODAWARI","GSPL",
"GSFC","GESHIP","HBLPOWER","HDFCAMC","HDFCBANK","HDFCLIFE","HFCL","HAPPSTMNDS",
"HAVELLS","HEROMOTOCO","HEG","HIKAL","HINDALCO","HAL","HINDCOPPER","HINDPETRO",
"HINDUNILVR","HITECH","HONAUT","HCLTECH","HDFCLIFE","HSCL","HUDCO","IBREALEST",
"ICICIBANK","ICICIGI","ICICIPRULI","ICRA","IDBI","IDFC","IDFCFIRSTB","IEX","IIFL",
"IIFLWAM","INDHOTEL","INDIANB","INDIACEM","INDIAMART","INDIGO","INDIGOPNTS","INDOCO",
"INDUSINDBK","INDUSTOWER","INFIBEAM","INFY","INGERRAND","INOXWIND","INTELLECT",
"IRB","IRCON","ISEC","ISGEC","ITC","ITI","J&KBANK","JBMA","JBCHEPHARM","JINDALSAW",
"JINDALSTEL","JKCEMENT","JKLAKSHMI","JKTYRE","JMFINANCIL","JODUMARG","JSWENERGY",
"JSWSTEEL","JUBLFOOD","JUBLPHARMA","JUSTDIAL","JYOTHYLAB","KALPATPOWR","KAMDHENU",
"KANSAINER","KARURVYSYA","KEI","KELLTON","KIRLOSBROS","KNRCON","KPITTECH","KPRMILL",
"KRBL","L&TFH","LTIM","LTTS","LICI","LUPIN","LUXIND","LXCHEM","LAURUSLABS",
"LOVABLE","M&M","M&MFIN","MAHLIFE","MANAPPURAM","MARICO","MARUTI","MASFIN","MASTEK",
"MAXHEALTH","MAZDOCK","MEDPLUS","METROPOLIS","MFSL","MGL","MHRIL","MIDHANI","MINDACORP",
"MINDAIND","MOTILALOFS","MPHASIS","MRF","MUTHOOTFIN","NATCOPHARM","NBCC","NCC","NESTLEIND",
"NETWORK18","NH","NHPC","NIACL","NIFTYBEES","NLCINDIA","NMDC","NTPC","NUVOCO","NYKAA",
"OBEROIRLTY","OFSS","OIL","ONGC","ORIENTELEC","PAGEIND","PEL","PERSISTENT","PETRONET",
"PFC","PFIZER","PIDILITIND","PIIND","PNB","PNBHOUSING","POLICYBZR","POLYCAB","POWERGRID",
"PPLPHARMA","PRAJIND","PRESTIGE","PSPPROJECT","PTC","RAIN","RAJESHEXPO","RALLIS",
"RAMCOCEM","RAMCOIND","RATNAMANI","RAYMOND","RBLBANK","RECLTD","REDINGTON","RELAXO",
"RELIANCE","REPCOHOME","ROSSARI","ROUTE","RPGLIFE","RPOWER","SAIL","SANOFI","SBICARD",
"SBILIFE","SBIN","SCHAEFFLER","SHARDACROP","SHK","SHOPERSTOP","SHREECEM","SHRIRAMFIN",
"SIEMENS","SJVN","SKFINDIA","SOLARINDS","SONACOMS","SONATSOFTW","SPARC","SRF","STARHEALTH",
"STLTECH","SUMICHEM","SUNPHARMA","SUNTV","SUNDARMFIN","SUPRAJIT","SUPREMEIND","SUVENPHAR",
"SUZLON","SYMPHONY","SYNGENE","TANLA","TASTYBITE","TATACHEM","TATACOMM","TATACONSUM",
"TATAELXSI","TATAMOTORS","TATAPOWER","TATASTEEL","TATATECH","TCI","TCNSBRANDS",
"TECHM","TIPSINDLTD","TITAN","TORNTPHARM","TORNTPOWER","TRENT","TRIDENT","TRIVENI",
"TTKPRESTIG","UCOBANK","ULTRACEMCO","UNOMINDA","UPL","UNIONBANK","UTIAMC","VGUARD",
"VOLTAS","WHIRLPOOL","WIPRO","YESBANK","ZEEL"
]
    
    return companies

@st.cache_data
def get_industry(company):
    keys = [key for key, val in nifty500_by_industry.items() if company in val]
    if len(keys) ==0:
        return ""
    return keys[0]