import streamlit as st
import re

stocks = {
    "360ONE": {'company': '360 ONE WAM Ltd.', 'industry': 'Financial Services'},
    "3MINDIA": {'company': '3M India Ltd.', 'industry': 'Diversified'},
    "ABB": {'company': 'ABB India Ltd.', 'industry': 'Capital Goods'},
    "ACC": {'company': 'ACC Ltd.', 'industry': 'Construction Materials'},
    "ACMESOLAR": {'company': 'ACME Solar Holdings Ltd.', 'industry': 'Power'},
    "AIAENG": {'company': 'AIA Engineering Ltd.', 'industry': 'Capital Goods'},
    "APLAPOLLO": {'company': 'APL Apollo Tubes Ltd.', 'industry': 'Capital Goods'},
    "AUBANK": {'company': 'AU Small Finance Bank Ltd.', 'industry': 'Financial Services'},
    "AWL": {'company': 'AWL Agri Business Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "AADHARHFC": {'company': 'Aadhar Housing Finance Ltd.', 'industry': 'Financial Services'},
    "AARTIIND": {'company': 'Aarti Industries Ltd.', 'industry': 'Chemicals'},
    "AAVAS": {'company': 'Aavas Financiers Ltd.', 'industry': 'Financial Services'},
    "ABBOTINDIA": {'company': 'Abbott India Ltd.', 'industry': 'Healthcare'},
    "ACE": {'company': 'Action Construction Equipment Ltd.', 'industry': 'Capital Goods'},
    "ADANIENSOL": {'company': 'Adani Energy Solutions Ltd.', 'industry': 'Power'},
    "ADANIENT": {'company': 'Adani Enterprises Ltd.', 'industry': 'Metals & Mining'},
    "ADANIGREEN": {'company': 'Adani Green Energy Ltd.', 'industry': 'Power'},
    "ADANIPORTS": {'company': 'Adani Ports and Special Economic Zone Ltd.', 'industry': 'Services'},
    "ADANIPOWER": {'company': 'Adani Power Ltd.', 'industry': 'Power'},
    "ATGL": {'company': 'Adani Total Gas Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "ABCAPITAL": {'company': 'Aditya Birla Capital Ltd.', 'industry': 'Financial Services'},
    "ABFRL": {'company': 'Aditya Birla Fashion and Retail Ltd.', 'industry': 'Consumer Services'},
    "ABLBL": {'company': 'Aditya Birla Lifestyle Brands Ltd.', 'industry': 'Consumer Services'},
    "ABREL": {'company': 'Aditya Birla Real Estate Ltd.', 'industry': 'Forest Materials'},
    "ABSLAMC": {'company': 'Aditya Birla Sun Life AMC Ltd.', 'industry': 'Financial Services'},
    "AEGISLOG": {'company': 'Aegis Logistics Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "AEGISVOPAK": {'company': 'Aegis Vopak Terminals Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "AFCONS": {'company': 'Afcons Infrastructure Ltd.', 'industry': 'Construction'},
    "AFFLE": {'company': 'Affle 3i Ltd.', 'industry': 'Information Technology'},
    "AJANTPHARM": {'company': 'Ajanta Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "AKUMS": {'company': 'Akums Drugs and Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "AKZOINDIA": {'company': 'Akzo Nobel India Ltd.', 'industry': 'Consumer Durables'},
    "APLLTD": {'company': 'Alembic Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "ALKEM": {'company': 'Alkem Laboratories Ltd.', 'industry': 'Healthcare'},
    "ALKYLAMINE": {'company': 'Alkyl Amines Chemicals Ltd.', 'industry': 'Chemicals'},
    "ALOKINDS": {'company': 'Alok Industries Ltd.', 'industry': 'Textiles'},
    "ARE&M": {'company': 'Amara Raja Energy & Mobility Ltd.', 'industry': 'Automobile and Auto Components'},
    "AMBER": {'company': 'Amber Enterprises India Ltd.', 'industry': 'Consumer Durables'},
    "AMBUJACEM": {'company': 'Ambuja Cements Ltd.', 'industry': 'Construction Materials'},
    "ANANDRATHI": {'company': 'Anand Rathi Wealth Ltd.', 'industry': 'Financial Services'},
    "ANANTRAJ": {'company': 'Anant Raj Ltd.', 'industry': 'Realty'},
    "ANGELONE": {'company': 'Angel One Ltd.', 'industry': 'Financial Services'},
    "APARINDS": {'company': 'Apar Industries Ltd.', 'industry': 'Capital Goods'},
    "APOLLOHOSP": {'company': 'Apollo Hospitals Enterprise Ltd.', 'industry': 'Healthcare'},
    "APOLLOTYRE": {'company': 'Apollo Tyres Ltd.', 'industry': 'Automobile and Auto Components'},
    "APTUS": {'company': 'Aptus Value Housing Finance India Ltd.', 'industry': 'Financial Services'},
    "ASAHIINDIA": {'company': 'Asahi India Glass Ltd.', 'industry': 'Automobile and Auto Components'},
    "ASHOKLEY": {'company': 'Ashok Leyland Ltd.', 'industry': 'Capital Goods'},
    "ASIANPAINT": {'company': 'Asian Paints Ltd.', 'industry': 'Consumer Durables'},
    "ASTERDM": {'company': 'Aster DM Healthcare Ltd.', 'industry': 'Healthcare'},
    "ASTRAZEN": {'company': 'AstraZenca Pharma India Ltd.', 'industry': 'Healthcare'},
    "ASTRAL": {'company': 'Astral Ltd.', 'industry': 'Capital Goods'},
    "ATHERENERG": {'company': 'Ather Energy Ltd.', 'industry': 'Automobile and Auto Components'},
    "ATUL": {'company': 'Atul Ltd.', 'industry': 'Chemicals'},
    "AUROPHARMA": {'company': 'Aurobindo Pharma Ltd.', 'industry': 'Healthcare'},
    "AIIL": {'company': 'Authum Investment & Infrastructure Ltd.', 'industry': 'Financial Services'},
    "DMART": {'company': 'Avenue Supermarts Ltd.', 'industry': 'Consumer Services'},
    "AXISBANK": {'company': 'Axis Bank Ltd.', 'industry': 'Financial Services'},
    "BASF": {'company': 'BASF India Ltd.', 'industry': 'Chemicals'},
    "BEML": {'company': 'BEML Ltd.', 'industry': 'Capital Goods'},
    "BLS": {'company': 'BLS International Services Ltd.', 'industry': 'Consumer Services'},
    "BSE": {'company': 'BSE Ltd.', 'industry': 'Financial Services'},
    "BAJAJ-AUTO": {'company': 'Bajaj Auto Ltd.', 'industry': 'Automobile and Auto Components'},
    "BAJFINANCE": {'company': 'Bajaj Finance Ltd.', 'industry': 'Financial Services'},
    "BAJAJFINSV": {'company': 'Bajaj Finserv Ltd.', 'industry': 'Financial Services'},
    "BAJAJHLDNG": {'company': 'Bajaj Holdings & Investment Ltd.', 'industry': 'Financial Services'},
    "BAJAJHFL": {'company': 'Bajaj Housing Finance Ltd.', 'industry': 'Financial Services'},
    "BALKRISIND": {'company': 'Balkrishna Industries Ltd.', 'industry': 'Automobile and Auto Components'},
    "BALRAMCHIN": {'company': 'Balrampur Chini Mills Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "BANDHANBNK": {'company': 'Bandhan Bank Ltd.', 'industry': 'Financial Services'},
    "BANKBARODA": {'company': 'Bank of Baroda', 'industry': 'Financial Services'},
    "BANKINDIA": {'company': 'Bank of India', 'industry': 'Financial Services'},
    "MAHABANK": {'company': 'Bank of Maharashtra', 'industry': 'Financial Services'},
    "BATAINDIA": {'company': 'Bata India Ltd.', 'industry': 'Consumer Durables'},
    "BAYERCROP": {'company': 'Bayer Cropscience Ltd.', 'industry': 'Chemicals'},
    "BERGEPAINT": {'company': 'Berger Paints India Ltd.', 'industry': 'Consumer Durables'},
    "BDL": {'company': 'Bharat Dynamics Ltd.', 'industry': 'Capital Goods'},
    "BEL": {'company': 'Bharat Electronics Ltd.', 'industry': 'Capital Goods'},
    "BHARATFORG": {'company': 'Bharat Forge Ltd.', 'industry': 'Automobile and Auto Components'},
    "BHEL": {'company': 'Bharat Heavy Electricals Ltd.', 'industry': 'Capital Goods'},
    "BPCL": {'company': 'Bharat Petroleum Corporation Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "BHARTIARTL": {'company': 'Bharti Airtel Ltd.', 'industry': 'Telecommunication'},
    "BHARTIHEXA": {'company': 'Bharti Hexacom Ltd.', 'industry': 'Telecommunication'},
    "BIKAJI": {'company': 'Bikaji Foods International Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "BIOCON": {'company': 'Biocon Ltd.', 'industry': 'Healthcare'},
    "BSOFT": {'company': 'Birlasoft Ltd.', 'industry': 'Information Technology'},
    "BLUEDART": {'company': 'Blue Dart Express Ltd.', 'industry': 'Services'},
    "BLUEJET": {'company': 'Blue Jet Healthcare Ltd.', 'industry': 'Healthcare'},
    "BLUESTARCO": {'company': 'Blue Star Ltd.', 'industry': 'Consumer Durables'},
    "BBTC": {'company': 'Bombay Burmah Trading Corporation Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "BOSCHLTD": {'company': 'Bosch Ltd.', 'industry': 'Automobile and Auto Components'},
    "FIRSTCRY": {'company': 'Brainbees Solutions Ltd.', 'industry': 'Consumer Services'},
    "BRIGADE": {'company': 'Brigade Enterprises Ltd.', 'industry': 'Realty'},
    "BRITANNIA": {'company': 'Britannia Industries Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "MAPMYINDIA": {'company': 'C.E. Info Systems Ltd.', 'industry': 'Information Technology'},
    "CCL": {'company': 'CCL Products (I) Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "CESC": {'company': 'CESC Ltd.', 'industry': 'Power'},
    "CGPOWER": {'company': 'CG Power and Industrial Solutions Ltd.', 'industry': 'Capital Goods'},
    "CRISIL": {'company': 'CRISIL Ltd.', 'industry': 'Financial Services'},
    "CAMPUS": {'company': 'Campus Activewear Ltd.', 'industry': 'Consumer Durables'},
    "CANFINHOME": {'company': 'Can Fin Homes Ltd.', 'industry': 'Financial Services'},
    "CANBK": {'company': 'Canara Bank', 'industry': 'Financial Services'},
    "CAPLIPOINT": {'company': 'Caplin Point Laboratories Ltd.', 'industry': 'Healthcare'},
    "CGCL": {'company': 'Capri Global Capital Ltd.', 'industry': 'Financial Services'},
    "CARBORUNIV": {'company': 'Carborundum Universal Ltd.', 'industry': 'Capital Goods'},
    "CASTROLIND": {'company': 'Castrol India Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "CEATLTD": {'company': 'Ceat Ltd.', 'industry': 'Automobile and Auto Components'},
    "CENTRALBK": {'company': 'Central Bank of India', 'industry': 'Financial Services'},
    "CDSL": {'company': 'Central Depository Services (India) Ltd.', 'industry': 'Financial Services'},
    "CENTURYPLY": {'company': 'Century Plyboards (India) Ltd.', 'industry': 'Consumer Durables'},
    "CERA": {'company': 'Cera Sanitaryware Ltd', 'industry': 'Consumer Durables'},
    "CHALET": {'company': 'Chalet Hotels Ltd.', 'industry': 'Consumer Services'},
    "CHAMBLFERT": {'company': 'Chambal Fertilizers & Chemicals Ltd.', 'industry': 'Chemicals'},
    "CHENNPETRO": {'company': 'Chennai Petroleum Corporation Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "CHOICEIN": {'company': 'Choice International Ltd.', 'industry': 'Financial Services'},
    "CHOLAHLDNG": {'company': 'Cholamandalam Financial Holdings Ltd.', 'industry': 'Financial Services'},
    "CHOLAFIN": {'company': 'Cholamandalam Investment and Finance Company Ltd.', 'industry': 'Financial Services'},
    "CIPLA": {'company': 'Cipla Ltd.', 'industry': 'Healthcare'},
    "CUB": {'company': 'City Union Bank Ltd.', 'industry': 'Financial Services'},
    "CLEAN": {'company': 'Clean Science and Technology Ltd.', 'industry': 'Chemicals'},
    "COALINDIA": {'company': 'Coal India Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "COCHINSHIP": {'company': 'Cochin Shipyard Ltd.', 'industry': 'Capital Goods'},
    "COFORGE": {'company': 'Coforge Ltd.', 'industry': 'Information Technology'},
    "COHANCE": {'company': 'Cohance Lifesciences Ltd.', 'industry': 'Healthcare'},
    "COLPAL": {'company': 'Colgate Palmolive (India) Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "CAMS": {'company': 'Computer Age Management Services Ltd.', 'industry': 'Financial Services'},
    "CONCORDBIO": {'company': 'Concord Biotech Ltd.', 'industry': 'Healthcare'},
    "CONCOR": {'company': 'Container Corporation of India Ltd.', 'industry': 'Services'},
    "COROMANDEL": {'company': 'Coromandel International Ltd.', 'industry': 'Chemicals'},
    "CRAFTSMAN": {'company': 'Craftsman Automation Ltd.', 'industry': 'Automobile and Auto Components'},
    "CREDITACC": {'company': 'CreditAccess Grameen Ltd.', 'industry': 'Financial Services'},
    "CROMPTON": {'company': 'Crompton Greaves Consumer Electricals Ltd.', 'industry': 'Consumer Durables'},
    "CUMMINSIND": {'company': 'Cummins India Ltd.', 'industry': 'Capital Goods'},
    "CYIENT": {'company': 'Cyient Ltd.', 'industry': 'Information Technology'},
    "DCMSHRIRAM": {'company': 'DCM Shriram Ltd.', 'industry': 'Diversified'},
    "DLF": {'company': 'DLF Ltd.', 'industry': 'Realty'},
    "DOMS": {'company': 'DOMS Industries Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "DABUR": {'company': 'Dabur India Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "DALBHARAT": {'company': 'Dalmia Bharat Ltd.', 'industry': 'Construction Materials'},
    "DATAPATTNS": {'company': 'Data Patterns (India) Ltd.', 'industry': 'Capital Goods'},
    "DEEPAKFERT": {'company': 'Deepak Fertilisers & Petrochemicals Corp. Ltd.', 'industry': 'Chemicals'},
    "DEEPAKNTR": {'company': 'Deepak Nitrite Ltd.', 'industry': 'Chemicals'},
    "DELHIVERY": {'company': 'Delhivery Ltd.', 'industry': 'Services'},
    "DEVYANI": {'company': 'Devyani International Ltd.', 'industry': 'Consumer Services'},
    "DIVISLAB": {'company': "Divi's Laboratories Ltd.", 'industry': 'Healthcare'},
    "DIXON": {'company': 'Dixon Technologies (India) Ltd.', 'industry': 'Consumer Durables'},
    "AGARWALEYE": {'company': "Dr. Agarwal's Health Care Ltd.", 'industry': 'Healthcare'},
    "LALPATHLAB": {'company': 'Dr. Lal Path Labs Ltd.', 'industry': 'Healthcare'},
    "DRREDDY": {'company': "Dr. Reddy's Laboratories Ltd.", 'industry': 'Healthcare'},
    "EIDPARRY": {'company': 'E.I.D. Parry (India) Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "EIHOTEL": {'company': 'EIH Ltd.', 'industry': 'Consumer Services'},
    "EICHERMOT": {'company': 'Eicher Motors Ltd.', 'industry': 'Automobile and Auto Components'},
    "ELECON": {'company': 'Elecon Engineering Co. Ltd.', 'industry': 'Capital Goods'},
    "ELGIEQUIP": {'company': 'Elgi Equipments Ltd.', 'industry': 'Capital Goods'},
    "EMAMILTD": {'company': 'Emami Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "EMCURE": {'company': 'Emcure Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "ENDURANCE": {'company': 'Endurance Technologies Ltd.', 'industry': 'Automobile and Auto Components'},
    "ENGINERSIN": {'company': 'Engineers India Ltd.', 'industry': 'Construction'},
    "ERIS": {'company': 'Eris Lifesciences Ltd.', 'industry': 'Healthcare'},
    "ESCORTS": {'company': 'Escorts Kubota Ltd.', 'industry': 'Capital Goods'},
    "ETERNAL": {'company': 'Eternal Ltd.', 'industry': 'Consumer Services'},
    "EXIDEIND": {'company': 'Exide Industries Ltd.', 'industry': 'Automobile and Auto Components'},
    "NYKAA": {'company': 'FSN E-Commerce Ventures Ltd.', 'industry': 'Consumer Services'},
    "FEDERALBNK": {'company': 'Federal Bank Ltd.', 'industry': 'Financial Services'},
    "FACT": {'company': 'Fertilisers and Chemicals Travancore Ltd.', 'industry': 'Chemicals'},
    "FINCABLES": {'company': 'Finolex Cables Ltd.', 'industry': 'Capital Goods'},
    "FINPIPE": {'company': 'Finolex Industries Ltd.', 'industry': 'Capital Goods'},
    "FSL": {'company': 'Firstsource Solutions Ltd.', 'industry': 'Services'},
    "FIVESTAR": {'company': 'Five-Star Business Finance Ltd.', 'industry': 'Financial Services'},
    "FORCEMOT": {'company': 'Force Motors Ltd.', 'industry': 'Automobile and Auto Components'},
    "FORTIS": {'company': 'Fortis Healthcare Ltd.', 'industry': 'Healthcare'},
    "GAIL": {'company': 'GAIL (India) Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "GVT&D": {'company': 'GE Vernova T&D India Ltd.', 'industry': 'Capital Goods'},
    "GMRAIRPORT": {'company': 'GMR Airports Ltd.', 'industry': 'Services'},
    "GRSE": {'company': 'Garden Reach Shipbuilders & Engineers Ltd.', 'industry': 'Capital Goods'},
    "GICRE": {'company': 'General Insurance Corporation of India', 'industry': 'Financial Services'},
    "GILLETTE": {'company': 'Gillette India Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "GLAND": {'company': 'Gland Pharma Ltd.', 'industry': 'Healthcare'},
    "GLAXO": {'company': 'Glaxosmithkline Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "GLENMARK": {'company': 'Glenmark Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "MEDANTA": {'company': 'Global Health Ltd.', 'industry': 'Healthcare'},
    "GODIGIT": {'company': 'Go Digit General Insurance Ltd.', 'industry': 'Financial Services'},
    "GPIL": {'company': 'Godawari Power & Ispat Ltd.', 'industry': 'Capital Goods'},
    "GODFRYPHLP": {'company': 'Godfrey Phillips India Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "GODREJAGRO": {'company': 'Godrej Agrovet Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "GODREJCP": {'company': 'Godrej Consumer Products Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "GODREJIND": {'company': 'Godrej Industries Ltd.', 'industry': 'Diversified'},
    "GODREJPROP": {'company': 'Godrej Properties Ltd.', 'industry': 'Realty'},
    "GRANULES": {'company': 'Granules India Ltd.', 'industry': 'Healthcare'},
    "GRAPHITE": {'company': 'Graphite India Ltd.', 'industry': 'Capital Goods'},
    "GRASIM": {'company': 'Grasim Industries Ltd.', 'industry': 'Construction Materials'},
    "GRAVITA": {'company': 'Gravita India Ltd.', 'industry': 'Metals & Mining'},
    "GESHIP": {'company': 'Great Eastern Shipping Co. Ltd.', 'industry': 'Services'},
    "FLUOROCHEM": {'company': 'Gujarat Fluorochemicals Ltd.', 'industry': 'Chemicals'},
    "GUJGASLTD": {'company': 'Gujarat Gas Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "GMDCLTD": {'company': 'Gujarat Mineral Development Corporation Ltd.', 'industry': 'Metals & Mining'},
    "GSPL": {'company': 'Gujarat State Petronet Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "HEG": {'company': 'H.E.G. Ltd.', 'industry': 'Capital Goods'},
    "HBLENGINE": {'company': 'HBL Engineering Ltd.', 'industry': 'Capital Goods'},
    "HCLTECH": {'company': 'HCL Technologies Ltd.', 'industry': 'Information Technology'},
    "HDFCAMC": {'company': 'HDFC Asset Management Company Ltd.', 'industry': 'Financial Services'},
    "HDFCBANK": {'company': 'HDFC Bank Ltd.', 'industry': 'Financial Services'},
    "HDFCLIFE": {'company': 'HDFC Life Insurance Company Ltd.', 'industry': 'Financial Services'},
    "HFCL": {'company': 'HFCL Ltd.', 'industry': 'Telecommunication'},
    "HAPPSTMNDS": {'company': 'Happiest Minds Technologies Ltd.', 'industry': 'Information Technology'},
    "HAVELLS": {'company': 'Havells India Ltd.', 'industry': 'Consumer Durables'},
    "HEROMOTOCO": {'company': 'Hero MotoCorp Ltd.', 'industry': 'Automobile and Auto Components'},
    "HEXT": {'company': 'Hexaware Technologies Ltd.', 'industry': 'Information Technology'},
    "HSCL": {'company': 'Himadri Speciality Chemical Ltd.', 'industry': 'Chemicals'},
    "HINDALCO": {'company': 'Hindalco Industries Ltd.', 'industry': 'Metals & Mining'},
    "HAL": {'company': 'Hindustan Aeronautics Ltd.', 'industry': 'Capital Goods'},
    "HINDCOPPER": {'company': 'Hindustan Copper Ltd.', 'industry': 'Metals & Mining'},
    "HINDPETRO": {'company': 'Hindustan Petroleum Corporation Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "HINDUNILVR": {'company': 'Hindustan Unilever Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "HINDZINC": {'company': 'Hindustan Zinc Ltd.', 'industry': 'Metals & Mining'},
    "POWERINDIA": {'company': 'Hitachi Energy India Ltd.', 'industry': 'Capital Goods'},
    "HOMEFIRST": {'company': 'Home First Finance Company India Ltd.', 'industry': 'Financial Services'},
    "HONASA": {'company': 'Honasa Consumer Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "HONAUT": {'company': 'Honeywell Automation India Ltd.', 'industry': 'Capital Goods'},
    "HUDCO": {'company': 'Housing & Urban Development Corporation Ltd.', 'industry': 'Financial Services'},
    "HYUNDAI": {'company': 'Hyundai Motor India Ltd.', 'industry': 'Automobile and Auto Components'},
    "ICICIBANK": {'company': 'ICICI Bank Ltd.', 'industry': 'Financial Services'},
    "ICICIGI": {'company': 'ICICI Lombard General Insurance Company Ltd.', 'industry': 'Financial Services'},
    "ICICIPRULI": {'company': 'ICICI Prudential Life Insurance Company Ltd.', 'industry': 'Financial Services'},
    "IDBI": {'company': 'IDBI Bank Ltd.', 'industry': 'Financial Services'},
    "IDFCFIRSTB": {'company': 'IDFC First Bank Ltd.', 'industry': 'Financial Services'},
    "IFCI": {'company': 'IFCI Ltd.', 'industry': 'Financial Services'},
    "IIFL": {'company': 'IIFL Finance Ltd.', 'industry': 'Financial Services'},
    "INOXINDIA": {'company': 'INOX India Ltd.', 'industry': 'Capital Goods'},
    "IRB": {'company': 'IRB Infrastructure Developers Ltd.', 'industry': 'Construction'},
    "IRCON": {'company': 'IRCON International Ltd.', 'industry': 'Construction'},
    "ITCHOTELS": {'company': 'ITC Hotels Ltd.', 'industry': 'Consumer Services'},
    "ITC": {'company': 'ITC Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "ITI": {'company': 'ITI Ltd.', 'industry': 'Telecommunication'},
    "INDGN": {'company': 'Indegene Ltd.', 'industry': 'Healthcare'},
    "INDIACEM": {'company': 'India Cements Ltd.', 'industry': 'Construction Materials'},
    "INDIAMART": {'company': 'Indiamart Intermesh Ltd.', 'industry': 'Consumer Services'},
    "INDIANB": {'company': 'Indian Bank', 'industry': 'Financial Services'},
    "IEX": {'company': 'Indian Energy Exchange Ltd.', 'industry': 'Financial Services'},
    "INDHOTEL": {'company': 'Indian Hotels Co. Ltd.', 'industry': 'Consumer Services'},
    "IOC": {'company': 'Indian Oil Corporation Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "IOB": {'company': 'Indian Overseas Bank', 'industry': 'Financial Services'},
    "IRCTC": {'company': 'Indian Railway Catering And Tourism Corporation Ltd.', 'industry': 'Consumer Services'},
    "IRFC": {'company': 'Indian Railway Finance Corporation Ltd.', 'industry': 'Financial Services'},
    "IREDA": {'company': 'Indian Renewable Energy Development Agency Ltd.', 'industry': 'Financial Services'},
    "IGL": {'company': 'Indraprastha Gas Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "INDUSTOWER": {'company': 'Indus Towers Ltd.', 'industry': 'Telecommunication'},
    "INDUSINDBK": {'company': 'IndusInd Bank Ltd.', 'industry': 'Financial Services'},
    "NAUKRI": {'company': 'Info Edge (India) Ltd.', 'industry': 'Consumer Services'},
    "INFY": {'company': 'Infosys Ltd.', 'industry': 'Information Technology'},
    "INOXWIND": {'company': 'Inox Wind Ltd.', 'industry': 'Capital Goods'},
    "INTELLECT": {'company': 'Intellect Design Arena Ltd.', 'industry': 'Information Technology'},
    "INDIGO": {'company': 'InterGlobe Aviation Ltd.', 'industry': 'Services'},
    "IGIL": {'company': 'International Gemmological Institute (India) Ltd.', 'industry': 'Services'},
    "IKS": {'company': 'Inventurus Knowledge Solutions Ltd.', 'industry': 'Information Technology'},
    "IPCALAB": {'company': 'Ipca Laboratories Ltd.', 'industry': 'Healthcare'},
    "JBCHEPHARM": {'company': 'J.B. Chemicals & Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "JKCEMENT": {'company': 'J.K. Cement Ltd.', 'industry': 'Construction Materials'},
    "JBMA": {'company': 'JBM Auto Ltd.', 'industry': 'Automobile and Auto Components'},
    "JKTYRE": {'company': 'JK Tyre & Industries Ltd.', 'industry': 'Automobile and Auto Components'},
    "JMFINANCIL": {'company': 'JM Financial Ltd.', 'industry': 'Financial Services'},
    "JSWENERGY": {'company': 'JSW Energy Ltd.', 'industry': 'Power'},
    "JSWINFRA": {'company': 'JSW Infrastructure Ltd.', 'industry': 'Services'},
    "JSWSTEEL": {'company': 'JSW Steel Ltd.', 'industry': 'Metals & Mining'},
    "JPPOWER": {'company': 'Jaiprakash Power Ventures Ltd.', 'industry': 'Power'},
    "J&KBANK": {'company': 'Jammu & Kashmir Bank Ltd.', 'industry': 'Financial Services'},
    "JINDALSAW": {'company': 'Jindal Saw Ltd.', 'industry': 'Capital Goods'},
    "JSL": {'company': 'Jindal Stainless Ltd.', 'industry': 'Metals & Mining'},
    "JINDALSTEL": {'company': 'Jindal Steel Ltd.', 'industry': 'Metals & Mining'},
    "JIOFIN": {'company': 'Jio Financial Services Ltd.', 'industry': 'Financial Services'},
    "JUBLFOOD": {'company': 'Jubilant Foodworks Ltd.', 'industry': 'Consumer Services'},
    "JUBLINGREA": {'company': 'Jubilant Ingrevia Ltd.', 'industry': 'Chemicals'},
    "JUBLPHARMA": {'company': 'Jubilant Pharmova Ltd.', 'industry': 'Healthcare'},
    "JWL": {'company': 'Jupiter Wagons Ltd.', 'industry': 'Capital Goods'},
    "JYOTHYLAB": {'company': 'Jyothy Labs Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "JYOTICNC": {'company': 'Jyoti CNC Automation Ltd.', 'industry': 'Capital Goods'},
    "KPRMILL": {'company': 'K.P.R. Mill Ltd.', 'industry': 'Textiles'},
    "KEI": {'company': 'KEI Industries Ltd.', 'industry': 'Capital Goods'},
    "KPITTECH": {'company': 'KPIT Technologies Ltd.', 'industry': 'Information Technology'},
    "KSB": {'company': 'KSB Ltd.', 'industry': 'Capital Goods'},
    "KAJARIACER": {'company': 'Kajaria Ceramics Ltd.', 'industry': 'Consumer Durables'},
    "KPIL": {'company': 'Kalpataru Projects International Ltd.', 'industry': 'Construction'},
    "KALYANKJIL": {'company': 'Kalyan Jewellers India Ltd.', 'industry': 'Consumer Durables'},
    "KARURVYSYA": {'company': 'Karur Vysya Bank Ltd.', 'industry': 'Financial Services'},
    "KAYNES": {'company': 'Kaynes Technology India Ltd.', 'industry': 'Capital Goods'},
    "KEC": {'company': 'Kec International Ltd.', 'industry': 'Construction'},
    "KFINTECH": {'company': 'Kfin Technologies Ltd.', 'industry': 'Financial Services'},
    "KIRLOSBROS": {'company': 'Kirloskar Brothers Ltd.', 'industry': 'Capital Goods'},
    "KIRLOSENG": {'company': 'Kirloskar Oil Eng Ltd.', 'industry': 'Capital Goods'},
    "KOTAKBANK": {'company': 'Kotak Mahindra Bank Ltd.', 'industry': 'Financial Services'},
    "KIMS": {'company': 'Krishna Institute of Medical Sciences Ltd.', 'industry': 'Healthcare'},
    "LTF": {'company': 'L&T Finance Ltd.', 'industry': 'Financial Services'},
    "LTTS": {'company': 'L&T Technology Services Ltd.', 'industry': 'Information Technology'},
    "LICHSGFIN": {'company': 'LIC Housing Finance Ltd.', 'industry': 'Financial Services'},
    "LTFOODS": {'company': 'LT Foods Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "LTIM": {'company': 'LTIMindtree Ltd.', 'industry': 'Information Technology'},
    "LT": {'company': 'Larsen & Toubro Ltd.', 'industry': 'Construction'},
    "LATENTVIEW": {'company': 'Latent View Analytics Ltd.', 'industry': 'Information Technology'},
    "LAURUSLABS": {'company': 'Laurus Labs Ltd.', 'industry': 'Healthcare'},
    "THELEELA": {'company': 'Leela Palaces Hotels & Resorts Ltd.', 'industry': 'Consumer Services'},
    "LEMONTREE": {'company': 'Lemon Tree Hotels Ltd.', 'industry': 'Consumer Services'},
    "LICI": {'company': 'Life Insurance Corporation of India', 'industry': 'Financial Services'},
    "LINDEINDIA": {'company': 'Linde India Ltd.', 'industry': 'Chemicals'},
    "LLOYDSME": {'company': 'Lloyds Metals And Energy Ltd.', 'industry': 'Metals & Mining'},
    "LODHA": {'company': 'Lodha Developers Ltd.', 'industry': 'Realty'},
    "LUPIN": {'company': 'Lupin Ltd.', 'industry': 'Healthcare'},
    "MMTC": {'company': 'MMTC Ltd.', 'industry': 'Services'},
    "MRF": {'company': 'MRF Ltd.', 'industry': 'Automobile and Auto Components'},
    "MGL": {'company': 'Mahanagar Gas Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "MAHSCOOTER": {'company': 'Maharashtra Scooters Ltd.', 'industry': 'Financial Services'},
    "MAHSEAMLES": {'company': 'Maharashtra Seamless Ltd.', 'industry': 'Capital Goods'},
    "M&MFIN": {'company': 'Mahindra & Mahindra Financial Services Ltd.', 'industry': 'Financial Services'},
    "M&M": {'company': 'Mahindra & Mahindra Ltd.', 'industry': 'Automobile and Auto Components'},
    "MANAPPURAM": {'company': 'Manappuram Finance Ltd.', 'industry': 'Financial Services'},
    "MRPL": {'company': 'Mangalore Refinery & Petrochemicals Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "MANKIND": {'company': 'Mankind Pharma Ltd.', 'industry': 'Healthcare'},
    "MARICO": {'company': 'Marico Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "MARUTI": {'company': 'Maruti Suzuki India Ltd.', 'industry': 'Automobile and Auto Components'},
    "MFSL": {'company': 'Max Financial Services Ltd.', 'industry': 'Financial Services'},
    "MAXHEALTH": {'company': 'Max Healthcare Institute Ltd.', 'industry': 'Healthcare'},
    "MAZDOCK": {'company': 'Mazagoan Dock Shipbuilders Ltd.', 'industry': 'Capital Goods'},
    "METROPOLIS": {'company': 'Metropolis Healthcare Ltd.', 'industry': 'Healthcare'},
    "MINDACORP": {'company': 'Minda Corporation Ltd.', 'industry': 'Automobile and Auto Components'},
    "MSUMI": {'company': 'Motherson Sumi Wiring India Ltd.', 'industry': 'Automobile and Auto Components'},
    "MOTILALOFS": {'company': 'Motilal Oswal Financial Services Ltd.', 'industry': 'Financial Services'},
    "MPHASIS": {'company': 'MphasiS Ltd.', 'industry': 'Information Technology'},
    "MCX": {'company': 'Multi Commodity Exchange of India Ltd.', 'industry': 'Financial Services'},
    "MUTHOOTFIN": {'company': 'Muthoot Finance Ltd.', 'industry': 'Financial Services'},
    "NATCOPHARM": {'company': 'NATCO Pharma Ltd.', 'industry': 'Healthcare'},
    "NBCC": {'company': 'NBCC (India) Ltd.', 'industry': 'Construction'},
    "NCC": {'company': 'NCC Ltd.', 'industry': 'Construction'},
    "NHPC": {'company': 'NHPC Ltd.', 'industry': 'Power'},
    "NLCINDIA": {'company': 'NLC India Ltd.', 'industry': 'Power'},
    "NMDC": {'company': 'NMDC Ltd.', 'industry': 'Metals & Mining'},
    "NSLNISP": {'company': 'NMDC Steel Ltd.', 'industry': 'Metals & Mining'},
    "NTPCGREEN": {'company': 'NTPC Green Energy Ltd.', 'industry': 'Power'},
    "NTPC": {'company': 'NTPC Ltd.', 'industry': 'Power'},
    "NH": {'company': 'Narayana Hrudayalaya Ltd.', 'industry': 'Healthcare'},
    "NATIONALUM": {'company': 'National Aluminium Co. Ltd.', 'industry': 'Metals & Mining'},
    "NAVA": {'company': 'Nava Ltd.', 'industry': 'Power'},
    "NAVINFLUOR": {'company': 'Navin Fluorine International Ltd.', 'industry': 'Chemicals'},
    "NESTLEIND": {'company': 'Nestle India Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "NETWEB": {'company': 'Netweb Technologies India Ltd.', 'industry': 'Information Technology'},
    "NEULANDLAB": {'company': 'Neuland Laboratories Ltd.', 'industry': 'Healthcare'},
    "NEWGEN": {'company': 'Newgen Software Technologies Ltd.', 'industry': 'Information Technology'},
    "NAM-INDIA": {'company': 'Nippon Life India Asset Management Ltd.', 'industry': 'Financial Services'},
    "NIVABUPA": {'company': 'Niva Bupa Health Insurance Company Ltd.', 'industry': 'Financial Services'},
    "NUVAMA": {'company': 'Nuvama Wealth Management Ltd.', 'industry': 'Financial Services'},
    "NUVOCO": {'company': 'Nuvoco Vistas Corporation Ltd.', 'industry': 'Construction Materials'},
    "OBEROIRLTY": {'company': 'Oberoi Realty Ltd.', 'industry': 'Realty'},
    "ONGC": {'company': 'Oil & Natural Gas Corporation Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "OIL": {'company': 'Oil India Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "OLAELEC": {'company': 'Ola Electric Mobility Ltd.', 'industry': 'Automobile and Auto Components'},
    "OLECTRA": {'company': 'Olectra Greentech Ltd.', 'industry': 'Automobile and Auto Components'},
    "PAYTM": {'company': 'One 97 Communications Ltd.', 'industry': 'Financial Services'},
    "ONESOURCE": {'company': 'Onesource Specialty Pharma Ltd.', 'industry': 'Healthcare'},
    "OFSS": {'company': 'Oracle Financial Services Software Ltd.', 'industry': 'Information Technology'},
    "POLICYBZR": {'company': 'PB Fintech Ltd.', 'industry': 'Financial Services'},
    "PCBL": {'company': 'PCBL Chemical Ltd.', 'industry': 'Chemicals'},
    "PGEL": {'company': 'PG Electroplast Ltd.', 'industry': 'Consumer Durables'},
    "PIIND": {'company': 'PI Industries Ltd.', 'industry': 'Chemicals'},
    "PNBHOUSING": {'company': 'PNB Housing Finance Ltd.', 'industry': 'Financial Services'},
    "PTCIL": {'company': 'PTC Industries Ltd.', 'industry': 'Capital Goods'},
    "PVRINOX": {'company': 'PVR INOX Ltd.', 'industry': 'Media Entertainment & Publication'},
    "PAGEIND": {'company': 'Page Industries Ltd.', 'industry': 'Textiles'},
    "PATANJALI": {'company': 'Patanjali Foods Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "PERSISTENT": {'company': 'Persistent Systems Ltd.', 'industry': 'Information Technology'},
    "PETRONET": {'company': 'Petronet LNG Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "PFIZER": {'company': 'Pfizer Ltd.', 'industry': 'Healthcare'},
    "PHOENIXLTD": {'company': 'Phoenix Mills Ltd.', 'industry': 'Realty'},
    "PIDILITIND": {'company': 'Pidilite Industries Ltd.', 'industry': 'Chemicals'},
    "PPLPHARMA": {'company': 'Piramal Pharma Ltd.', 'industry': 'Healthcare'},
    "POLYMED": {'company': 'Poly Medicure Ltd.', 'industry': 'Healthcare'},
    "POLYCAB": {'company': 'Polycab India Ltd.', 'industry': 'Capital Goods'},
    "POONAWALLA": {'company': 'Poonawalla Fincorp Ltd.', 'industry': 'Financial Services'},
    "PFC": {'company': 'Power Finance Corporation Ltd.', 'industry': 'Financial Services'},
    "POWERGRID": {'company': 'Power Grid Corporation of India Ltd.', 'industry': 'Power'},
    "PRAJIND": {'company': 'Praj Industries Ltd.', 'industry': 'Capital Goods'},
    "PREMIERENE": {'company': 'Premier Energies Ltd.', 'industry': 'Capital Goods'},
    "PRESTIGE": {'company': 'Prestige Estates Projects Ltd.', 'industry': 'Realty'},
    "PGHH": {'company': 'Procter & Gamble Hygiene & Health Care Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "PNB": {'company': 'Punjab National Bank', 'industry': 'Financial Services'},
    "RRKABEL": {'company': 'R R Kabel Ltd.', 'industry': 'Capital Goods'},
    "RBLBANK": {'company': 'RBL Bank Ltd.', 'industry': 'Financial Services'},
    "RECLTD": {'company': 'REC Ltd.', 'industry': 'Financial Services'},
    "RHIM": {'company': 'RHI MAGNESITA INDIA LTD.', 'industry': 'Capital Goods'},
    "RITES": {'company': 'RITES Ltd.', 'industry': 'Construction'},
    "RADICO": {'company': 'Radico Khaitan Ltd', 'industry': 'Fast Moving Consumer Goods'},
    "RVNL": {'company': 'Rail Vikas Nigam Ltd.', 'industry': 'Construction'},
    "RAILTEL": {'company': 'Railtel Corporation Of India Ltd.', 'industry': 'Telecommunication'},
    "RAINBOW": {'company': 'Rainbow Childrens Medicare Ltd.', 'industry': 'Healthcare'},
    "RKFORGE": {'company': 'Ramkrishna Forgings Ltd.', 'industry': 'Automobile and Auto Components'},
    "RCF": {'company': 'Rashtriya Chemicals & Fertilizers Ltd.', 'industry': 'Chemicals'},
    "REDINGTON": {'company': 'Redington Ltd.', 'industry': 'Services'},
    "RELIANCE": {'company': 'Reliance Industries Ltd.', 'industry': 'Oil Gas & Consumable Fuels'},
    "RELINFRA": {'company': 'Reliance Infrastructure Ltd.', 'industry': 'Power'},
    "RPOWER": {'company': 'Reliance Power Ltd.', 'industry': 'Power'},
    "SBFC": {'company': 'SBFC Finance Ltd.', 'industry': 'Financial Services'},
    "SBICARD": {'company': 'SBI Cards and Payment Services Ltd.', 'industry': 'Financial Services'},
    "SBILIFE": {'company': 'SBI Life Insurance Company Ltd.', 'industry': 'Financial Services'},
    "SJVN": {'company': 'SJVN Ltd.', 'industry': 'Power'},
    "SKFINDUS": {'company': 'SKF India (Industrial) Ltd.', 'industry': 'Capital Goods'},
    "SKFINDIA": {'company': 'SKF India Ltd.', 'industry': 'Automobile and Auto Components'},
    "SRF": {'company': 'SRF Ltd.', 'industry': 'Chemicals'},
    "SAGILITY": {'company': 'Sagility Ltd.', 'industry': 'Information Technology'},
    "SAILIFE": {'company': 'Sai Life Sciences Ltd.', 'industry': 'Healthcare'},
    "SAMMAANCAP": {'company': 'Sammaan Capital Ltd.', 'industry': 'Financial Services'},
    "MOTHERSON": {'company': 'Samvardhana Motherson International Ltd.', 'industry': 'Automobile and Auto Components'},
    "SAPPHIRE": {'company': 'Sapphire Foods India Ltd.', 'industry': 'Consumer Services'},
    "SARDAEN": {'company': 'Sarda Energy and Minerals Ltd.', 'industry': 'Metals & Mining'},
    "SAREGAMA": {'company': 'Saregama India Ltd', 'industry': 'Media Entertainment & Publication'},
    "SCHAEFFLER": {'company': 'Schaeffler India Ltd.', 'industry': 'Automobile and Auto Components'},
    "SCHNEIDER": {'company': 'Schneider Electric Infrastructure Ltd.', 'industry': 'Capital Goods'},
    "SCI": {'company': 'Shipping Corporation of India Ltd.', 'industry': 'Services'},
    "SHREECEM": {'company': 'Shree Cement Ltd.', 'industry': 'Construction Materials'},
    "SHRIRAMFIN": {'company': 'Shriram Finance Ltd.', 'industry': 'Financial Services'},
    "SHYAMMETL": {'company': 'Shyam Metalics and Energy Ltd.', 'industry': 'Capital Goods'},
    "ENRIN": {'company': 'Siemens Energy India Ltd.', 'industry': 'Capital Goods'},
    "SIEMENS": {'company': 'Siemens Ltd.', 'industry': 'Capital Goods'},
    "SIGNATURE": {'company': 'Signatureglobal (India) Ltd.', 'industry': 'Realty'},
    "SOBHA": {'company': 'Sobha Ltd.', 'industry': 'Realty'},
    "SOLARINDS": {'company': 'Solar Industries India Ltd.', 'industry': 'Chemicals'},
    "SONACOMS": {'company': 'Sona BLW Precision Forgings Ltd.', 'industry': 'Automobile and Auto Components'},
    "SONATSOFTW": {'company': 'Sonata Software Ltd.', 'industry': 'Information Technology'},
    "STARHEALTH": {'company': 'Star Health and Allied Insurance Company Ltd.', 'industry': 'Financial Services'},
    "SBIN": {'company': 'State Bank of India', 'industry': 'Financial Services'},
    "SAIL": {'company': 'Steel Authority of India Ltd.', 'industry': 'Metals & Mining'},
    "SUMICHEM": {'company': 'Sumitomo Chemical India Ltd.', 'industry': 'Chemicals'},
    "SUNPHARMA": {'company': 'Sun Pharmaceutical Industries Ltd.', 'industry': 'Healthcare'},
    "SUNTV": {'company': 'Sun TV Network Ltd.', 'industry': 'Media Entertainment & Publication'},
    "SUNDARMFIN": {'company': 'Sundaram Finance Ltd.', 'industry': 'Financial Services'},
    "SUNDRMFAST": {'company': 'Sundram Fasteners Ltd.', 'industry': 'Automobile and Auto Components'},
    "SUPREMEIND": {'company': 'Supreme Industries Ltd.', 'industry': 'Capital Goods'},
    "SUZLON": {'company': 'Suzlon Energy Ltd.', 'industry': 'Capital Goods'},
    "SWANCORP": {'company': 'Swan Corp Ltd.', 'industry': 'Chemicals'},
    "SWIGGY": {'company': 'Swiggy Ltd.', 'industry': 'Consumer Services'},
    "SYNGENE": {'company': 'Syngene International Ltd.', 'industry': 'Healthcare'},
    "SYRMA": {'company': 'Syrma SGS Technology Ltd.', 'industry': 'Capital Goods'},
    "TBOTEK": {'company': 'TBO Tek Ltd.', 'industry': 'Consumer Services'},
    "TVSMOTOR": {'company': 'TVS Motor Company Ltd.', 'industry': 'Automobile and Auto Components'},
    "TATACHEM": {'company': 'Tata Chemicals Ltd.', 'industry': 'Chemicals'},
    "TATACOMM": {'company': 'Tata Communications Ltd.', 'industry': 'Telecommunication'},
    "TCS": {'company': 'Tata Consultancy Services Ltd.', 'industry': 'Information Technology'},
    "TATACONSUM": {'company': 'Tata Consumer Products Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "TATAELXSI": {'company': 'Tata Elxsi Ltd.', 'industry': 'Information Technology'},
    "TATAINVEST": {'company': 'Tata Investment Corporation Ltd.', 'industry': 'Financial Services'},
    "TMPV": {'company': 'Tata Motors Passenger Vehicles Ltd.', 'industry': 'Automobile and Auto Components'},
    "TATAPOWER": {'company': 'Tata Power Co. Ltd.', 'industry': 'Power'},
    "TATASTEEL": {'company': 'Tata Steel Ltd.', 'industry': 'Metals & Mining'},
    "TATATECH": {'company': 'Tata Technologies Ltd.', 'industry': 'Information Technology'},
    "TTML": {'company': 'Tata Teleservices (Maharashtra) Ltd.', 'industry': 'Telecommunication'},
    "TECHM": {'company': 'Tech Mahindra Ltd.', 'industry': 'Information Technology'},
    "TECHNOE": {'company': 'Techno Electric & Engineering Company Ltd.', 'industry': 'Construction'},
    "TEJASNET": {'company': 'Tejas Networks Ltd.', 'industry': 'Telecommunication'},
    "NIACL": {'company': 'The New India Assurance Company Ltd.', 'industry': 'Financial Services'},
    "RAMCOCEM": {'company': 'The Ramco Cements Ltd.', 'industry': 'Construction Materials'},
    "THERMAX": {'company': 'Thermax Ltd.', 'industry': 'Capital Goods'},
    "TIMKEN": {'company': 'Timken India Ltd.', 'industry': 'Capital Goods'},
    "TITAGARH": {'company': 'Titagarh Rail Systems Ltd.', 'industry': 'Capital Goods'},
    "TITAN": {'company': 'Titan Company Ltd.', 'industry': 'Consumer Durables'},
    "TORNTPHARM": {'company': 'Torrent Pharmaceuticals Ltd.', 'industry': 'Healthcare'},
    "TORNTPOWER": {'company': 'Torrent Power Ltd.', 'industry': 'Power'},
    "TARIL": {'company': 'Transformers And Rectifiers (India) Ltd.', 'industry': 'Capital Goods'},
    "TRENT": {'company': 'Trent Ltd.', 'industry': 'Consumer Services'},
    "TRIDENT": {'company': 'Trident Ltd.', 'industry': 'Textiles'},
    "TRIVENI": {'company': 'Triveni Engineering & Industries Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "TRITURBINE": {'company': 'Triveni Turbine Ltd.', 'industry': 'Capital Goods'},
    "TIINDIA": {'company': 'Tube Investments of India Ltd.', 'industry': 'Automobile and Auto Components'},
    "UCOBANK": {'company': 'UCO Bank', 'industry': 'Financial Services'},
    "UNOMINDA": {'company': 'UNO Minda Ltd.', 'industry': 'Automobile and Auto Components'},
    "UPL": {'company': 'UPL Ltd.', 'industry': 'Chemicals'},
    "UTIAMC": {'company': 'UTI Asset Management Company Ltd.', 'industry': 'Financial Services'},
    "ULTRACEMCO": {'company': 'UltraTech Cement Ltd.', 'industry': 'Construction Materials'},
    "UNIONBANK": {'company': 'Union Bank of India', 'industry': 'Financial Services'},
    "UBL": {'company': 'United Breweries Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "UNITDSPR": {'company': 'United Spirits Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "USHAMART": {'company': 'Usha Martin Ltd.', 'industry': 'Capital Goods'},
    "VGUARD": {'company': 'V-Guard Industries Ltd.', 'industry': 'Consumer Durables'},
    "DBREALTY": {'company': 'Valor Estate Ltd.', 'industry': 'Consumer Services'},
    "VTL": {'company': 'Vardhman Textiles Ltd.', 'industry': 'Textiles'},
    "VBL": {'company': 'Varun Beverages Ltd.', 'industry': 'Fast Moving Consumer Goods'},
    "MANYAVAR": {'company': 'Vedant Fashions Ltd.', 'industry': 'Consumer Services'},
    "VEDL": {'company': 'Vedanta Ltd.', 'industry': 'Metals & Mining'},
    "VENTIVE": {'company': 'Ventive Hospitality Ltd.', 'industry': 'Consumer Services'},
    "VIJAYA": {'company': 'Vijaya Diagnostic Centre Ltd.', 'industry': 'Healthcare'},
    "VMM": {'company': 'Vishal Mega Mart Ltd.', 'industry': 'Consumer Services'},
    "IDEA": {'company': 'Vodafone Idea Ltd.', 'industry': 'Telecommunication'},
    "VOLTAS": {'company': 'Voltas Ltd.', 'industry': 'Consumer Durables'},
    "WAAREEENER": {'company': 'Waaree Energies Ltd.', 'industry': 'Capital Goods'},
    "WELCORP": {'company': 'Welspun Corp Ltd.', 'industry': 'Capital Goods'},
    "WELSPUNLIV": {'company': 'Welspun Living Ltd.', 'industry': 'Textiles'},
    "WHIRLPOOL": {'company': 'Whirlpool of India Ltd.', 'industry': 'Consumer Durables'},
    "WIPRO": {'company': 'Wipro Ltd.', 'industry': 'Information Technology'},
    "WOCKPHARMA": {'company': 'Wockhardt Ltd.', 'industry': 'Healthcare'},
    "YESBANK": {'company': 'Yes Bank Ltd.', 'industry': 'Financial Services'},
    "ZFCVINDIA": {'company': 'ZF Commercial Vehicle Control Systems India Ltd.', 'industry': 'Automobile and Auto Components'},
    "ZEEL": {'company': 'Zee Entertainment Enterprises Ltd.', 'industry': 'Media Entertainment & Publication'},
    "ZENTEC": {'company': 'Zen Technologies Ltd.', 'industry': 'Capital Goods'},
    "ZENSARTECH": {'company': 'Zensar Technolgies Ltd.', 'industry': 'Information Technology'},
    "ZYDUSLIFE": {'company': 'Zydus Lifesciences Ltd.', 'industry': 'Healthcare'},
    "ECLERX": {'company': 'eClerx Services Ltd.', 'industry': 'Services'},
}


def get_company_symbols():
    return stocks.keys()

@st.cache_data
def get_industry(company):
    return stocks[company]['industry']

@st.cache_data
def get_company_name(company):
    return stocks[company]['company']


    

def normalize_name(name: str) -> str:
    name = name.lower()
    name = re.sub(r'\b(limited|ltd)\b', '', name)
    name = re.sub(r'[^a-z0-9 ]', '', name)
    name = re.sub(r'\s+', ' ', name)
    return name.strip()