create table public.nse_announcement_insights (
  id bigint generated by default as identity not null,
  "Date" date null,
  "Symbol" text null,
  "Title" text null default ''''''::text,
  "Sentiment_Score" real null default '0'::real,
  "Reason" text null default ''''''::text,
  "Link" text null default ''''''::text,
  "Published_Time" timestamp with time zone null,
  constraint nse_announcement_insights_pkey primary key (id)
) TABLESPACE pg_default;



create table public.stocks (
  id bigint generated by default as identity not null,
  symbol text not null,
  industry text null,
  created_at timestamp without time zone null default now(),
  company text null,
  constraint stocks_id_key unique (id),
  constraint stocks_symbol_key unique (symbol)
) TABLESPACE pg_default;


create table if not exists daily_prices (
    id bigserial primary key,
    stock_id bigint references stocks(id) on delete cascade,
    trade_date date not null,
    open numeric,
    high numeric,
    low numeric,
    close numeric,
    adj_close numeric,
    volume bigint,

    created_at timestamp default now(),
    unique(stock_id, trade_date)
);

create table if not exists daily_metrics (
    id bigserial primary key,
    stock_id bigint references stocks(id) on delete cascade,
    trade_date date not null,

    current_price numeric,
    ma_14 numeric,
    ma_30 numeric,
    ma_60 numeric,

    pct_change_14 numeric,
    pct_change_30 numeric,
    pct_change_60 numeric,

    rsi_14 numeric,
    rsi_30 numeric,
    rsi_60 numeric,

    created_at timestamp default now(),
    unique(stock_id, trade_date)
);

create index if not exists idx_prices_stock_date
on daily_prices(stock_id, trade_date desc);

create index if not exists idx_prices_date
on daily_prices(trade_date);

create index if not exists idx_metrics_stock_date
on daily_metrics(stock_id, trade_date desc);
